export const mockData = [
  {
    Id: 1,
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@techcorp.com",
    phone: "+1 (555) 123-4567",
    companyId: 1,
    companyName: "TechCorp Solutions",
    title: "VP of Sales",
    tags: ["hot-lead", "enterprise"],
    notes: "Interested in our enterprise package. Follow up next week.",
    createdAt: "2024-01-15T10:30:00Z"
  },
  {
    Id: 2,
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@innovatetech.com",
    phone: "+1 (555) 234-5678",
    companyId: 2,
    companyName: "InnovateTech",
    title: "CTO",
    tags: ["technical", "decision-maker"],
    notes: "Needs technical demo. Prefers afternoon meetings.",
    createdAt: "2024-01-18T14:15:00Z"
  },
  {
    Id: 3,
    firstName: "Emily",
    lastName: "Rodriguez",
    email: "emily.rodriguez@growthstartup.com",
    phone: "+1 (555) 345-6789",
    companyId: 3,
    companyName: "Growth Startup",
    title: "Founder & CEO",
    tags: ["startup", "quick-decision"],
    notes: "Very interested in our startup package. Budget approved.",
    createdAt: "2024-01-20T09:45:00Z"
  },
  {
    Id: 4,
    firstName: "David",
    lastName: "Thompson",
    email: "david.thompson@globalsystems.com",
    phone: "+1 (555) 456-7890",
    companyId: 4,
    companyName: "Global Systems Inc",
    title: "IT Director",
    tags: ["enterprise", "long-cycle"],
    notes: "Large enterprise deal. Requires board approval.",
    createdAt: "2024-01-22T11:20:00Z"
  },
  {
    Id: 5,
    firstName: "Jessica",
    lastName: "Williams",
    email: "jessica.williams@creativeagency.com",
    phone: "+1 (555) 567-8901",
    companyId: 5,
    companyName: "Creative Agency",
    title: "Creative Director",
    tags: ["creative", "design-focused"],
    notes: "Loves our design tools. Wants custom branding options.",
    createdAt: "2024-01-25T16:30:00Z"
  },
  {
    Id: 6,
    firstName: "Robert",
    lastName: "Garcia",
    email: "robert.garcia@retailchain.com",
    phone: "+1 (555) 678-9012",
    companyId: 6,
    companyName: "Retail Chain Co",
    title: "Operations Manager",
    tags: ["retail", "cost-conscious"],
    notes: "Price sensitive. Interested in volume discounts.",
    createdAt: "2024-01-28T13:45:00Z"
  },
  {
    Id: 7,
    firstName: "Amanda",
    lastName: "Foster",
    email: "amanda.foster@financecorp.com",
    phone: "+1 (555) 789-0123",
    companyId: 7,
    companyName: "Finance Corp",
    title: "CFO",
    tags: ["finance", "compliance"],
    notes: "Requires detailed security and compliance documentation.",
    createdAt: "2024-02-01T10:15:00Z"
  },
  {
    Id: 8,
    firstName: "Christopher",
    lastName: "Lee",
    email: "chris.lee@manufactureplus.com",
    phone: "+1 (555) 890-1234",
    companyId: 8,
    companyName: "Manufacture Plus",
    title: "Plant Manager",
    tags: ["manufacturing", "efficiency"],
    notes: "Focused on operational efficiency improvements.",
    createdAt: "2024-02-03T15:20:00Z"
  }
]